"""Mines already-published roundup posts for resolved PR-author credits.

Every post in posts/ was generated by a run that already paid the cost of
looking up (via GitHub's API) who authored a PR a changelog bullet didn't
already credit inline, then baked the result into the post text. This reads
that back for free instead of re-querying GitHub for the same PR.
"""

import re
from pathlib import Path
from typing import Dict, Optional

# Matches "[#123](pull-request-url) ([login](https://github.com/login))" --
# a PR reference immediately followed by an author-credit link, which is the
# exact shape 02_fetch_release_notes.py's enrichment produces.
_CREDITED_PR_RE = re.compile(
    r'\[#\d+\]\((https://github\.com/[^/]+/[^/]+/pull/\d+)\)\s*'
    r'\(\[([A-Za-z0-9_-]+)\]\(https://github\.com/[A-Za-z0-9_-]+\)\)'
)


def build_pr_author_cache(posts_dir: Optional[Path] = None) -> Dict[str, str]:
    """Scan posts_dir/*.md for credited PR references and return {pr_url: login}.

    No network calls. Returns an empty dict if posts_dir doesn't exist.
    """
    posts_dir = Path(posts_dir) if posts_dir else Path("posts")
    cache: Dict[str, str] = {}
    if not posts_dir.exists():
        return cache

    for md_file in sorted(posts_dir.glob("*.md")):
        text = md_file.read_text(encoding="utf-8")
        for pr_url, login in _CREDITED_PR_RE.findall(text):
            cache[pr_url] = login

    return cache
